

---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: k8s-db-oidc
  namespace: {{ .Release.Namespace }}
spec:
  level: 20
  root: o=Tremolo
  authMechs:
{{ if eq (.Values.openunison.non_secret_data.K8S_DB_SSO | default "oidc") "oidc" }}
  - name: oidc
    required: required
    params:
      bearerTokenName: k8s-ou
      clientid: openunison
      responseType: code
      idpURL: "https://#[OU_HOST]/auth/idp/k8sIdp/auth"
      loadTokenURL: "https://#[OU_HOST]/auth/idp/k8sIdp/token"
      scope: "openid name offline"
      linkToDirectory: "true"
      noMatchOU: "oidc"
      lookupFilter: "(sub=${sub})"
      defaultObjectClass: inetOrgPerson
      uidAttr: sub
      hd: ""
      userLookupClassName: com.tremolosecurity.unison.proxy.auth.openidconnect.loadUser.LoadJWTFromAccessToken
      jwtTokenAttributeName: id_token
    secretParams:
    - name: secretid
      secretName: orchestra-secrets-source
      secretKey: K8S_DB_SECRET
{{ else }}
  - name: saml2
    required: required
    params:
      idpURL: "https://#[OU_HOST]/auth/idp/k8sdb-saml2/httpPost"
      idpRedirURL: "https://#[OU_HOST]/auth/idp/k8sdb-saml2/httpRedirect"
      idpSigKeyName: unison-saml2-rp-sig
      ldapAttribute: sub
      dnOU: saml2
      defaultOC: inetOrgPerson
      authCtxRef: "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
      spSigKey: unison-saml2-rp-sig
      idpRedirLogoutURL: "https://#[OU_HOST]/logout"
      logoutURL: ""
      sigAlg: RSA-SHA256
      entityID: "https://#[OU_HOST]/auth/idp/k8sdb-saml2"
      signAuthnReq: "true"
      assertionsSigned: "false"
      responsesSigned: "true"
      assertionEncrypted: "false"
      spEncKey: ""
      forceToSSL: "false"
      jumpPage: ""
      dontLinkToLDAP: "false"
      triggerLogoutURL: "https://#[OU_HOST]/logout"
{{ end }}
  - name: genoidctoken
    required: required
    params:
      idpName: k8sIdp
      trustName: kubernetes
      overrideURL: "https://#[OU_HOST]/auth/idp/k8sIdp"